# Day 3 Assignment
## 1. Create a 2D matrix and multiply every element by 2 and print both the arrays

In [1]:
import numpy as np
import pandas as pd

In [4]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = arr1 * 2
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


## 2. Use Pandas to create a Dataframe from a dictionary. The dictionary should contain data for atleast three products, with columns for product_name, price and stock_quantity

In [9]:
data = {
    'product_name':['Smart Table','Normal Table','Teakwood Table','Chair'],
    'price':[8900,5800,9500,2500],
    'stock_quantity':[25,30,75,137]
}

print(type(data))
print(data)


<class 'dict'>
{'product_name': ['Smart Table', 'Normal Table', 'Teakwood Table', 'Chair'], 'price': [8900, 5800, 9500, 2500], 'stock_quantity': [25, 30, 75, 137]}


In [10]:
df = pd.DataFrame(data)
df.head()

product_name  price  stock_quantity
0     Smart Table   8900              25
1    Normal Table   5800              30
2  Teakwood Table   9500              75
3           Chair   2500             137

# Use pandas to perform a data filtering operation to find and print only the products with stock_quantity greater than 50.

In [11]:
filtered_df = df[df['stock_quantity'] > 50]
print(filtered_df)

     product_name  price  stock_quantity
2  Teakwood Table   9500              75
3           Chair   2500             137


In [12]:
filtered_df.head()

product_name  price  stock_quantity
2  Teakwood Table   9500              75
3           Chair   2500             137