# Functions
### Function Definition

In [5]:
def student_info(name, age=18):
    print(name,age)

### Function Calling

In [6]:
student_info("John")
student_info("Alice",98)

John 18
Alice 98


# Numpy
### Installing Numpy 

In [7]:
!pip install numpy

### Importing Numpy

In [8]:
import numpy as np

### Numpy array

In [17]:
x = np.array([1,2,3])                       #1D array
y = np.array([[1,2,3],[4,5,6]])                #2D array
z = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])        #3D array
print(x,"\n")
print(y,"\n")
print(z,"\n")

[1 2 3] 

[[1 2 3]
 [4 5 6]] 

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] 



# Pandas

In [18]:
!pip install pandas

In [19]:
import pandas as pd

# Series and Dataframe
#### Pandas can be used to convert a list to a Series and a 2d array into a Dataframe

In [20]:
s = pd.Series([10,20,30,40], name = "myNumbers")
print(f"Type of Series:{type(s)}")

Type of Series:<class 'pandas.core.series.Series'>


In [27]:
data = {
    'Name':['Alice','Bob','David','Nina'],
    'Age':[25,30,35,25],
    'City':['NYC','London','Paris','NYC'],
    'Salary':[70000,58000,95000,75000]
}

print(type(data))
print(data)


<class 'dict'>
{'Name': ['Alice', 'Bob', 'David', 'Nina'], 'Age': [25, 30, 35, 25], 'City': ['NYC', 'London', 'Paris', 'NYC'], 'Salary': [70000, 58000, 95000, 75000]}


In [26]:
df = pd.DataFrame(data)
df.head()

Name  Age    City  Salary
0  Alice   25     NYC   70000
1    Bob   30  London   58000
2  David   35   Paris   95000
3   Nina   25     NYC   75000

### Read CSV

In [30]:
df = pd.read_csv('hearing-well-being.csv')

In [31]:
df.head()

Perceived_Hearing_Meaning Hearing_FOMO  \
0  Staying independent and alert, Enjoying music,...    Sometimes   
1  Staying independent and alert, Staying connect...       Rarely   
2  Staying independent and alert, I haven’t tho...       Rarely   
3                      Staying independent and alert    Yes often   
4                      Staying independent and alert        Never   

  Hearing_Test_Barrier                            Missed_Important_Sounds  \
0                 Cost                       Yes, in family conversations   
1  Never felt the need  Yes, in public spaces (trains, shops, announce...   
2                Shame      Yes, during important work or school meetings   
3    Lack of awareness      Yes, during important work or school meetings   
4    Lack of awareness                     No, I usually hear things well   

  Left_Out_Due_To_Hearing Daily_Headphone_Use  Belief_Early_Hearing_Care  \
0              Yes, often        My parent(s)                          5   
1    Only in noisy places   My child/children                          5   
2               Sometimes        My parent(s)                          5   
3               Sometimes           1-2 hours                          4   
4    Only in noisy places    Less than 1 hour                          5   

                    Last_Hearing_Test_Method  \
0  Self - application, Loved one, AI Support   
1                         Self - application   
2                         Self - application   
3            I've never taken a hearing test   
4            I've never taken a hearing test   

            Interest_in_Hearing_App  \
0                               Yes   
1                               Yes   
2                             Maybe   
3        Yes, that would be helpful   
4  No, I don't think it's necessary   

                                Desired_App_Features  \
0  Privacy, Soft guidance, Visuals, Report sharin...   
1                                            Privacy   
2                                      Soft guidance   
3                             Game-based interaction   
4  Quick tests, Game-based interaction, Detailed ...   

  Awareness_on_hearing_and_Willingness_to_invest  \
0                                            Yes   
1                                            Yes   
2                                             No   
3                                            Yes   
4                                             No   

                      Paid_App_Test_Interest Age_group  \
0             Maybe, if it offers good value   18 - 24   
1  No, I prefer getting tested at a hospital   18 - 24   
2                            Yes, definitely   18 - 24   
3                            Yes, definitely   18 - 24   
4  No, I prefer getting tested at a hospital   25 - 34   

  Ear_Discomfort_After_Use  
0                       No  
1                      Yes  
2                    Maybe  
3             Occasionally  
4                       No